"""Generated consumer/protocol harnesses for package audits.

The harness is deliberately generated by Lotus and executed in the isolated
lab.  It never executes a command supplied by a repository or a lead.  Each
scenario has an explicit ``completed``/``skipped``/``failed`` result so a
library audit cannot silently become a package-import smoke test.
"""
from __future__ import annotations

import asyncio
import json
import re
import time
from pathlib import Path
from typing import Any, Dict, Optional


_NODE_HARNESS = r'''/* Lotus-generated consumer harness; do not edit. */
const fs = require("fs");
const path = require("path");
const http = require("http");
const https = require("https");
const crypto = require("crypto");
const { URL } = require("url");
const { createRequire } = require("module");
const appRequire = createRequire("/app/package.json");
process.chdir("/app");
const pkgName = process.env.LOTUS_PACKAGE || ".";
const harnessMode = process.env.LOTUS_HARNESS_MODE || "full";
const out = {schema_version: 1, package: pkgName, runtime: process.version,
  mode: harnessMode,
  scenarios: [], fuzz: {iterations: 0, crashes: 0, exceptions: 0, inputs: []},
  security_observations: [],
  coverage: {requested: Boolean(process.env.NODE_V8_COVERAGE), directory: process.env.NODE_V8_COVERAGE || ""}};
function scenario(name, status, detail) { out.scenarios.push({name, status, ...(detail || {})}); }
function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
function request(url, opts, body) {
  return new Promise((resolve, reject) => {
    const u = new URL(url); const mod = u.protocol === "https:" ? https : http;
    const req = mod.request({...opts, protocol: u.protocol, hostname: u.hostname,
      port: u.port, path: u.pathname + u.search, rejectUnauthorized: false,
      timeout: opts.timeout || 1200}, res => {
      let data = ""; res.setEncoding("utf8"); res.on("data", d => data += d);
      res.on("end", () => resolve({statusCode: res.statusCode, headers: res.headers, body: data}));
    });
    req.on("timeout", () => req.destroy(new Error("timeout")));
    req.on("error", reject); if (body) req.write(body); req.end();
  });
}
function loadPackage() {
  try {
    // The generated script is executed from /tmp inside the lab.  Node resolves
    // ``require('.')`` relative to the script file (not process.cwd()), so a
    // naive package_name="." incorrectly loads /tmp and always fails.  Resolve
    // relative package selectors against the mounted enrolled tree explicitly.
    const target = (pkgName === "." || pkgName.startsWith("./") || pkgName.startsWith("../"))
      ? path.resolve("/app", pkgName) : pkgName;
    return {value: appRequire(target)};
  }
  catch (e) { return {error: String(e && (e.stack || e.message) || e)}; }
}
function proxyFactory(mod) {
  if (!mod) return null;
  if (typeof mod.createProxyServer === "function") return mod.createProxyServer.bind(mod);
  if (typeof mod === "function") return (opts) => mod(opts);
  if (mod.default && typeof mod.default.createProxyServer === "function") return mod.default.createProxyServer.bind(mod.default);
  return null;
}
async function httpScenario(mod, variant) {
  const factory = proxyFactory(mod); if (!factory) {
    scenario("http-" + variant, "skipped", {reason: "package has no recognized createProxyServer consumer API"}); return;
  }
  // A separate origin lets the harness test the security boundary around
  // followRedirects.  A same-origin 302 only proves redirect plumbing; it
  // cannot detect credential/header leakage to an attacker-controlled host.
  let captured = {};
  const sink = http.createServer((req, res) => {
    captured = {apiKey: req.headers["x-api-key"] || "", proxyAuthorization: req.headers["proxy-authorization"] || ""};
    res.setHeader("content-type", "application/json");
    res.end(JSON.stringify({captured: Boolean(captured.apiKey || captured.proxyAuthorization)}));
  });
  await new Promise(r => sink.listen(0, "127.0.0.1", r));
  const sinkPort = sink.address().port;
  const target = http.createServer((req, res) => {
    res.setHeader("x-lotus-target", "1");
    if (req.url === "/redirect") { res.writeHead(302, {location: "/final"}); return res.end("redirect"); }
    if (req.url === "/cross-redirect") {
      res.writeHead(302, {location: "http://127.0.0.1:" + sinkPort + "/capture"});
      return res.end("cross-redirect");
    }
    if (req.url === "/slow") return setTimeout(() => res.end("slow"), 250);
    res.end("ok:" + req.url);
  });
  await new Promise(r => target.listen(0, "127.0.0.1", r));
  const targetPort = target.address().port;
  let proxy;
    try { proxy = factory({}); } catch (e) {
    scenario("http-" + variant, "failed", {error: String(e && e.message || e)});
    target.close(); sink.close(); return;
  }
  if (!proxy || typeof proxy.web !== "function") {
    scenario("http-" + variant, "skipped", {reason: "consumer object has no web(req,res,opts) API"});
    target.close(); sink.close(); return;
  }
  const server = http.createServer((req, res) => {
    try { proxy.web(req, res, {target: "http://127.0.0.1:" + targetPort,
      changeOrigin: variant === "change-origin", xfwd: variant === "forwarded",
      followRedirects: variant === "follow-redirects"}); }
    catch (e) { res.statusCode = 500; res.end("proxy-error:" + e.message); }
  });
  await new Promise(r => server.listen(0, "127.0.0.1", r));
  const port = server.address().port; const checks = {};
  try {
    const normal = await request("http://127.0.0.1:" + port + "/normal", {headers: {"x-lotus-input": "consumer"}});
    checks.normal = {status: normal.statusCode, targetHeader: normal.headers["x-lotus-target"] || ""};
    const redirected = await request("http://127.0.0.1:" + port + "/redirect", {headers: {"x-lotus-redirect": "1"}});
    checks.redirect = {status: redirected.statusCode, location: redirected.headers.location || ""};
    const cross = await request("http://127.0.0.1:" + port + "/cross-redirect", {
      headers: {"x-api-key": "lotus-harness-secret", "proxy-authorization": "Basic lotus-harness-secret"}
    });
    checks.crossOriginRedirect = {status: cross.statusCode, sinkCaptured: Boolean(captured.apiKey || captured.proxyAuthorization),
      apiKey: Boolean(captured.apiKey), proxyAuthorization: Boolean(captured.proxyAuthorization)};
    if (variant === "follow-redirects" && checks.crossOriginRedirect.sinkCaptured) {
      out.security_observations.push({
        kind: "cross-origin-auth-header-leak", severity: "high",
        evidence: checks.crossOriginRedirect,
        reason: "followRedirects forwarded a custom authentication header to a different origin"
      });
    }
    try { await request("http://127.0.0.1:" + port + "/slow", {timeout: 80}); checks.timeout = "response"; }
    catch (e) { checks.timeout = String(e && e.message || e); }
    scenario("http-" + variant, "completed", {checks});
  } catch (e) { scenario("http-" + variant, "failed", {error: String(e && (e.stack || e.message) || e), checks}); }
  await new Promise(r => server.close(r)); await new Promise(r => target.close(r)); await new Promise(r => sink.close(r));
}
async function httpsScenario(mod) {
  const factory = proxyFactory(mod);
  const candidates = [["/app/test/fixtures/agent2-key.pem", "/app/test/fixtures/agent2-cert.pem"],
    ["/app/test/fixtures/key.pem", "/app/test/fixtures/cert.pem"]];
  const pair = candidates.find(p => fs.existsSync(p[0]) && fs.existsSync(p[1]));
  if (!factory) { scenario("https", "skipped", {reason: "package has no recognized consumer API"}); return; }
  if (!pair) { scenario("https", "skipped", {reason: "no approved ephemeral certificate fixture in isolated lab"}); return; }
  const target = https.createServer({key: fs.readFileSync(pair[0]), cert: fs.readFileSync(pair[1])}, (req, res) => {
    res.setHeader("x-lotus-tls", "1"); res.end("tls-ok");
  });
  await new Promise(r => target.listen(0, "127.0.0.1", r));
  const targetPort = target.address().port; let proxy;
  try { proxy = factory({}); } catch (e) { scenario("https", "failed", {error: String(e && e.message || e)}); target.close(); return; }
  if (!proxy || typeof proxy.web !== "function") { scenario("https", "skipped", {reason: "consumer object has no web(req,res,opts) API"}); target.close(); return; }
  const server = http.createServer((req, res) => {
    try { proxy.web(req, res, {target: "https://127.0.0.1:" + targetPort, secure: false, changeOrigin: true}); }
    catch (e) { res.statusCode = 500; res.end("proxy-error:" + e.message); }
  });
  await new Promise(r => server.listen(0, "127.0.0.1", r));
  try {
    const result = await request("http://127.0.0.1:" + server.address().port + "/tls", {timeout: 1500});
    scenario("https", result.statusCode === 200 && result.body === "tls-ok" ? "completed" : "failed",
      {http_status: result.statusCode, body: result.body, tlsHeader: result.headers["x-lotus-tls"] || ""});
  } catch (e) { scenario("https", "failed", {error: String(e && e.message || e)}); }
  await new Promise(r => server.close(r)); await new Promise(r => target.close(r));
}
async function configurationScenario(mod) {
  const factory = proxyFactory(mod);
  const variants = [
    {},
    {changeOrigin: true},
    {xfwd: true},
    {followRedirects: true},
    {secure: false, timeout: 100, agent: false}
  ];
  if (!factory) {
    scenario("configuration-variants", "skipped", {reason: "package has no recognized consumer API"});
    return;
  }
  let constructed = 0; const errors = [];
  for (const config of variants) {
    try {
      const instance = factory(config);
      if (!instance) errors.push("factory returned no consumer"); else constructed++;
    } catch (e) { errors.push(String(e && e.message || e)); }
  }
  scenario("configuration-variants", errors.length ? "failed" : "completed", {
    variants: variants.length, constructed, errors: errors.slice(0, 5)
  });
}
async function websocketScenario(mod) {
  let ws; try { ws = appRequire("ws"); } catch (_) { ws = null; }
  const factory = proxyFactory(mod);
  if (!ws || !factory) { scenario("websocket", "skipped", {reason: !ws ? "ws module unavailable" : "package has no recognized consumer API"}); return; }
  let proxy; try { proxy = factory({}); } catch (e) { scenario("websocket", "failed", {error: String(e && e.message || e)}); return; }
  if (!proxy || typeof proxy.ws !== "function") { scenario("websocket", "skipped", {reason: "consumer object has no ws(req,socket,head,opts) API"}); return; }
  const targetHttp = http.createServer(); const targetWs = new ws.Server({server: targetHttp});
  targetWs.on("connection", socket => socket.on("message", data => socket.send("echo:" + data.toString())));
  await new Promise(r => targetHttp.listen(0, "127.0.0.1", r));
  const targetPort = targetHttp.address().port;
  const server = http.createServer();
  server.on("upgrade", (req, socket, head) => {
    try { proxy.ws(req, socket, head, {target: "ws://127.0.0.1:" + targetPort}); }
    catch (e) { try { socket.destroy(); } catch (_) {} }
  });
  await new Promise(r => server.listen(0, "127.0.0.1", r));
  const WebSocketCtor = ws.WebSocket || ws;
  const client = new WebSocketCtor("ws://127.0.0.1:" + server.address().port + "/echo");
  try {
    const message = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("websocket timeout")), 1500);
      client.on("open", () => client.send("lotus"));
      client.on("message", value => { clearTimeout(timer); resolve(value.toString()); });
      client.on("error", error => { clearTimeout(timer); reject(error); });
    });
    scenario("websocket", message === "echo:lotus" ? "completed" : "failed", {message});
  } catch (e) { scenario("websocket", "failed", {error: String(e && e.message || e)}); }
  try { client.close(); } catch (_) {}
  await new Promise(r => server.close(r)); await new Promise(r => targetHttp.close(r));
}
async function fuzzScenario(mod) {
  const factory = proxyFactory(mod); const inputs = [null, {}, {target: ""}, {target: "http://127.0.0.1:1", timeout: 1}, {target: "not-a-url"}, {changeOrigin: true, xfwd: true}];
  out.fuzz.iterations = inputs.length; out.fuzz.inputs = inputs.map(x => x === null ? "null" : JSON.stringify(x));
  if (!factory) { scenario("public-api-fuzz", "skipped", {reason: "package has no recognized consumer API"}); return; }
  for (const input of inputs) { try { factory(input); } catch (_) { out.fuzz.exceptions++; } }
  scenario("public-api-fuzz", "completed", {iterations: out.fuzz.iterations, exceptions: out.fuzz.exceptions, crashes: 0});
}
(async () => {
  const loaded = loadPackage(); if (loaded.error) { out.status = "failed"; out.error = loaded.error; console.log("LOTUS_HARNESS_JSON=" + JSON.stringify(out)); process.exitCode = 2; return; }
  const mod = loaded.value; out.export_type = typeof mod; out.exports = mod && typeof mod === "object" ? Object.keys(mod).slice(0, 40) : [];
  if (harnessMode !== "fuzz") {
    await httpScenario(mod, "default"); await httpScenario(mod, "change-origin"); await httpScenario(mod, "forwarded"); await httpScenario(mod, "follow-redirects");
    await configurationScenario(mod); await httpsScenario(mod); await websocketScenario(mod);
  }
  if (harnessMode !== "protocol") await fuzzScenario(mod);
  out.status = out.scenarios.some(s => s.status === "failed") ? "failed" : "completed";
  console.log("LOTUS_HARNESS_JSON=" + JSON.stringify(out));
})().catch(e => { out.status = "failed"; out.error = String(e && (e.stack || e.message) || e); console.log("LOTUS_HARNESS_JSON=" + JSON.stringify(out)); process.exitCode = 2; });
'''


def _parse_marker(stdout: str) -> Dict[str, Any]:
    matches = re.findall(r"LOTUS_HARNESS_JSON=(\{.*\})", stdout or "")
    if not matches:
        return {"schema_version": 1, "status": "failed", "error": "harness marker missing"}
    try:
        obj = json.loads(matches[-1])
        return obj if isinstance(obj, dict) else {"schema_version": 1, "status": "failed", "error": "invalid harness object"}
    except Exception as exc:
        return {"schema_version": 1, "status": "failed", "error": f"invalid harness JSON: {exc}"}


async def run_node_library_harness(
    repo_id: int,
    dest: Path,
    *,
    package_name: str = ".",
    mode: str = "full",
    send=None,
    timeout: int = 90,
) -> Dict[str, Any]:
    """Run the generated Node consumer harness in the target lab."""
    if not (Path(dest) / "package.json").is_file():
        return {"schema_version": 1, "status": "skipped", "reason": "package.json missing"}
    from backend import lab
    if not lab.get_lab_container(repo_id):
        return {"schema_version": 1, "status": "skipped", "reason": "isolated lab container unavailable"}
    started = time.monotonic()
    script = Path(dest) / ".lotus" / "generated_harnesses" / "node_consumer.js"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(_NODE_HARNESS, encoding="utf-8")
    # Source snapshots are commonly read-only at runtime.  The script is part
    # of the image copied into /app; V8 writes coverage to /tmp only.
    import base64
    encoded = base64.b64encode(_NODE_HARNESS.encode("utf-8")).decode("ascii")
    # ``package_name`` originates from the enrolled package metadata.  It is
    # still treated as data at the shell boundary; JSON quoting is not shell
    # quoting, so use a strict single-quote helper for the environment value.
    shell_quote = lambda value: "'" + str(value).replace("'", "'\\''") + "'"
    safe_mode = mode if mode in {"full", "protocol", "fuzz"} else "full"
    command = (
        "rm -rf /tmp/lotus-v8-coverage /tmp/lotus-node-consumer.js; mkdir -p /tmp/lotus-v8-coverage; "
        f"printf %s {encoded} | base64 -d > /tmp/lotus-node-consumer.js; "
        f"LOTUS_PACKAGE={shell_quote(package_name)} LOTUS_HARNESS_MODE={shell_quote(safe_mode)} "
        "NODE_V8_COVERAGE=/tmp/lotus-v8-coverage "
        "node /tmp/lotus-node-consumer.js; rc=$?; "
        "printf '\\nLOTUS_COVERAGE_FILES=%s\\n' \"$(find /tmp/lotus-v8-coverage -type f -name '*.json' 2>/dev/null | wc -l)\"; exit $rc"
    )
    result = await lab.exec_in_lab(repo_id, command, timeout=timeout)
    artifact = _parse_marker((result.get("stdout") or "") + "\n" + (result.get("stderr") or ""))
    coverage_match = re.search(r"LOTUS_COVERAGE_FILES=(\d+)", result.get("stdout") or "")
    artifact.setdefault("coverage", {})["files"] = int(coverage_match.group(1)) if coverage_match else 0
    artifact["duration_seconds"] = round(time.monotonic() - started, 3)
    artifact["exit_code"] = result.get("exit_code")
    # The marker is untrusted process output.  A successful-looking marker
    # from a timed-out/non-zero container command must never override the
    # executor's exit status.
    if not result.get("success") and artifact.get("status") == "completed":
        artifact["status"] = "failed"
        artifact["error"] = str(result.get("stderr") or "harness process exited unsuccessfully")[-500:]
    scenarios = artifact.get("scenarios") or []
    if artifact.get("status") == "completed" and scenarios and all(
        isinstance(row, dict) and row.get("status") == "skipped" for row in scenarios
    ):
        artifact["status"] = "skipped"
        artifact.setdefault("reason", "all generated consumer/protocol scenarios were unsupported")
    artifact["command"] = (
        f"LOTUS_HARNESS_MODE={safe_mode} "
        "NODE_V8_COVERAGE=/tmp/lotus-v8-coverage node /tmp/lotus-node-consumer.js"
    )
    artifact["stdout_tail"] = (result.get("stdout") or "")[-3000:]
    artifact["stderr_tail"] = (result.get("stderr") or "")[-1500:]
    # Keep the historical default filename for API compatibility; protocol and
    # fuzz executions get independent immutable artifacts so the second task
    # cannot overwrite evidence from the first.
    artifact_name = "node_consumer_harness.json" if safe_mode == "full" else f"node_consumer_harness_{safe_mode}.json"
    artifact_path = Path(dest) / ".lotus" / artifact_name
    artifact_path.write_text(json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8")
    if send:
        await send(repo_id, f"Node consumer harness: {artifact.get('status')} ({len(artifact.get('scenarios') or [])} scenarios, V8 files={artifact.get('coverage', {}).get('files', 0)})")
    return artifact


async def run_generic_library_harness(
    repo_id: int,
    dest: Path,
    *,
    language: str,
    mode: str = "protocol",
    send=None,
) -> Dict[str, Any]:
    """Persist an explicit adapter result for non-Node libraries.

    Protocol semantics are library-specific outside Node, so pretending that a
    Java/Python/Go/Rust package was exercised by the Node consumer would be a
    dangerous false negative.  Until a language adapter is installed, emit a
    generated, durable scenario matrix with terminal ``skipped`` rows.  This
    keeps the requirement visible in the plan/report and gives future adapters
    a stable artifact contract rather than silently omitting the work.
    """
    language = str(language or "unknown").lower()
    safe_mode = mode if mode in {"protocol", "fuzz"} else "protocol"
    if safe_mode == "fuzz":
        names = ["public-api-fuzz", "coverage-instrumentation"]
    else:
        names = [
            "http-default", "http-change-origin", "http-forwarded",
            "http-follow-redirects", "https", "websocket",
            "headers", "timeout", "configuration-variants",
        ]
    reason = f"no validated {language} consumer/protocol adapter is installed"
    artifact: Dict[str, Any] = {
        "schema_version": 1,
        "status": "skipped",
        "language": language,
        "mode": safe_mode,
        "reason": reason,
        "scenarios": [{"name": name, "status": "skipped", "reason": reason} for name in names],
        "coverage": {"requested": True, "files": 0, "instrumentation": "unavailable"},
        "fuzz": {"iterations": 0, "crashes": 0, "exceptions": 0},
        "security_observations": [],
    }
    artifact_path = Path(dest) / ".lotus" / "generated_harnesses" / f"{language}_consumer_{safe_mode}.json"
    try:
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        artifact_path.write_text(json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8")
        artifact["artifact_path"] = str(artifact_path)
    except OSError as exc:
        artifact["artifact_write_error"] = str(exc)[:300]
    if send:
        await send(repo_id, f"{language} consumer harness: skipped ({reason})", level="warning")
    return artifact
