apiVersion: v1
kind: ConfigMap
metadata:
  name: lotus-controller-kubeconfig
  namespace: lotus
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: local-cluster
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: controller
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: lotus-in-cluster
        context:
          cluster: local-cluster
          user: controller
          namespace: lotus
    current-context: lotus-in-cluster
