apiVersion: v1
kind: Namespace
metadata:
  name: lotus-build
  labels:
    app: lotus
    lotus.io/role: builder
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
