apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lotus
resources:
  - ../../base
  - postgres.yaml
  - secret.yaml
  - hpa.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: lotus
